services:
  gin:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      pgsql:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: always

  pgsql:
    image: docker.io/postgres:18.3-alpine
    environment:
      POSTGRES_USER: ${PGSQL_USER}
      POSTGRES_PASSWORD: ${PGSQL_PASSWORD}
      POSTGRES_DB: ${PGSQL_NAME}
      TZ: Asia/Kolkata
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PGSQL_USER} -d ${PGSQL_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  redis:
    image: docker.io/valkey/valkey:9.0.3-alpine
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "valkey-cli", "-h", "127.0.0.1", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  pgdata:
  redisdata:
